name: trademate_app
description: "TradeMate Mobile Application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.1.0
  flutter_tabler_icons: ^1.43.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  persistent_bottom_nav_bar: ^6.2.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  web_socket_channel: ^3.0.3
  logger: ^2.5.0
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - .env
